SELECT  A.NAME
  FROM  STUDENTS AS A
 INNER 
  JOIN  PACKAGES AS B
    ON  A.ID = B.ID
 INNER
  JOIN  FRIENDS AS C
    ON  A.ID = C.ID
 INNER
  JOIN  PACKAGES AS D
    ON  C.FRIEND_ID = D.ID
 WHERE  D.SALARY > B.SALARY 
 ORDER
    BY  D.SALARY