SELECT  A.HACKER_ID
        ,D.NAME
  FROM  SUBMISSIONS AS A
 INNER
  JOIN  CHALLENGES AS B
    ON  A.CHALLENGE_ID = B.CHALLENGE_ID
 INNER
  JOIN  DIFFICULTY AS C
    ON  B.DIFFICULTY_LEVEL = C.DIFFICULTY_LEVEL
 INNER
  JOIN  HACKERS AS D
    ON  A.HACKER_ID = D.HACKER_ID
 WHERE  A.SCORE = C.SCORE
 GROUP  
    BY  A.HACKER_ID
        ,D.NAME
HAVING  COUNT(A.HACKER_ID) > 1
 ORDER
    BY  COUNT(A.HACKER_ID) DESC
        ,A.HACKER_ID ASC