-- HACKERRANK 문제 Employee Names
SELECT  NAME
  FROM  EMPLOYEE
 ORDER
    BY  NAME

-- HACKERRANK 문제 Employee Salary
SELECT  NAME
  FROM  EMPLOYEE
 WHERE  SALARY > 2000
   AND  MONTHS < 10
 ORDER
    BY  EMPLOYEE_ID ASC
    
-- HACKERRANK 문제 Higher Than 75 Marks
SELECT  NAME
  FROM  STUDENTS
 WHERE  MARKS > 75
 ORDER
    BY  RIGHT(NAME,3)
        , ID
        
SELECT  NAME
  FROM  STUDENTS
 WHERE  MARKS > 75
 ORDER
    BY  SUBSTR(NAME,-3)
        , ID

-- HACKERRANK 문제 Weather Observation Station 15
SELECT  ROUND(LONG_W,4)
  FROM  STATION
 WHERE  LAT_N < 137.2345
 ORDER 
    BY  LAT_N DESC
 LIMIT  1